CREATE TABLE IF NOT EXISTS github.issues (
    url TEXT,
    repository_url TEXT,
    labels_url TEXT,
    comments_url TEXT,
    events_url TEXT,
    html_url TEXT,
    id TEXT,
    node_id TEXT,
    number TEXT,
    title TEXT,
    "user" TEXT,
    labels TEXT,
    state TEXT,
    locked TEXT,
    assignees TEXT,
    milestone TEXT,
    comments TEXT,
    created_at TEXT,
    updated_at TEXT,
    closed_at TEXT,
    assignee TEXT,
    author_association TEXT,
    type TEXT,
    active_lock_reason TEXT,
    draft TEXT,
    pull_request TEXT,
    body TEXT,
    closed_by TEXT,
    reactions TEXT,
    timeline_url TEXT,
    performed_via_github_app TEXT,
    state_reason TEXT,
    ingested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);