name: 'dbt_open_source_lens'
version: '1.0.0'

profile: 'dbt_open_source_lens'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"

models:
  dbt_open_source_lens:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
